stages:
  - test

build project:
  image: maven:3.6-jdk-8-slim
  stage: test
  script:
    - echo "<----Initiate test project---->"
    - mvn -B -DskipTests clean package
    - echo "<----Finish build stage---->"
    - mvn test
    - echo "<----Finish test stage---->"